resources:
  - name: cowsay-src
    type: git
    source:
      uri: https://github.com/jrussett/cowsay-pipeline.git
      branch: master

  - name: slack-alert
    type: slack-notification
    source:
      url: ((slack_url))

jobs:
  - name: cowsay
    plan:
      - get: cowsay-src
        trigger: true
      - task: cowsay-run
        file: cowsay-src/ci/cowsay-task.yml
      - put: slack-alert
        params:
          text_file: cowsay-output/output.txt
