resources:
  - name: cowsay-src
    type: git
    source:
      uri: https://github.com/jrussett/cowsay-pipeline.git
      branch: master

jobs:
  - name: cowsay
    plan:
      - get: cowsay-src
      - task: cowsay-run
        file: cowsay-src/ci/cowsay-task.yml
